spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: pelicula-service
          uri: lb://pelicula-service
          predicates:
            - Path=/api/peliculas/**
          filters:
            - StripPrefix=1

        - id: categoria-service
          uri: lb://categoria-service
          predicates:
            - Path=/api/categorias/**
          filters:
            - StripPrefix=1

