server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: pelicula-service
          uri: lb://pelicula-service
          predicates:
            - Path=/peliculas/**
