spring:
  main:
    web-application-type: reactive  #  ¡MUY IMPORTANTE!

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: pelicula-service
              uri: lb://pelicula-service
              predicates:
                - Path=/api/peliculas/**
              filters:
                - StripPrefix=1
